class MockBangumiItem {
  final int id;
  final String nameCn;
  final String name;
  final String imageUrl;
  final String airDate;
  final double ratingScore;
  final int votes;
  final int rank;
  final String summary;

  const MockBangumiItem({
    required this.id,
    required this.nameCn,
    required this.name,
    required this.imageUrl,
    this.airDate = '',
    this.ratingScore = 0,
    this.votes = 0,
    this.rank = 0,
    this.summary = '',
  });
}

final List<MockBangumiItem> mockBangumiList = [
  const MockBangumiItem(
    id: 1,
    nameCn: '进击的巨人 最终季',
    name: 'Shingeki no Kyojin: The Final Season',
    imageUrl: 'https://picsum.photos/seed/aot/300/460',
    airDate: '2020-12-07',
    ratingScore: 8.6,
    votes: 3820,
    rank: 128,
    summary: '「那一天，人类终于回忆起了，曾经一度被他们所支配的恐怖，还有被囚禁于鸟笼中的那份屈辱。」',
  ),
  const MockBangumiItem(
    id: 2,
    nameCn: '鬼灭之刃 柱训练篇',
    name: 'Kimetsu no Yaiba: Hashira Geiko-hen',
    imageUrl: 'https://picsum.photos/seed/kimetsu/300/460',
    airDate: '2024-05-12',
    ratingScore: 7.2,
    votes: 1560,
    rank: 892,
    summary: '炭治郎为了变得更强而接受柱们的训练。',
  ),
  const MockBangumiItem(
    id: 3,
    nameCn: '葬送的芙莉莲',
    name: 'Sousou no Frieren',
    imageUrl: 'https://picsum.photos/seed/frieren/300/460',
    airDate: '2023-09-29',
    ratingScore: 9.1,
    votes: 5200,
    rank: 15,
    summary: '魔王被勇者一行打倒了。经历漫长旅途回到王都的勇者一行，目睹了半世纪才一次的流星雨。',
  ),
  const MockBangumiItem(
    id: 4,
    nameCn: '咒术回战 涩谷事变',
    name: 'Jujutsu Kaisen 2nd Season',
    imageUrl: 'https://picsum.photos/seed/jjk2/300/460',
    airDate: '2023-07-06',
    ratingScore: 8.4,
    votes: 4100,
    rank: 156,
    summary: '2018年10月31日——涩谷被帷降下。',
  ),
  const MockBangumiItem(
    id: 5,
    nameCn: '间谍过家家 第二季',
    name: 'SPY×FAMILY Season 2',
    imageUrl: 'https://picsum.photos/seed/spy2/300/460',
    airDate: '2023-10-07',
    ratingScore: 7.8,
    votes: 2890,
    rank: 420,
    summary: '为了世界和平，间谍的虚假家庭继续着日常生活。',
  ),
  const MockBangumiItem(
    id: 6,
    nameCn: '药屋少女的呢喃',
    name: 'Kusuriya no Hitorigoto',
    imageUrl: 'https://picsum.photos/seed/kusuriya/300/460',
    airDate: '2024-01-13',
    ratingScore: 8.7,
    votes: 3400,
    rank: 89,
    summary: '大陆中央的某个大国。被卖到后宫做宫女的猫猫，利用药学知识解决后宫的种种事件。',
  ),
  const MockBangumiItem(
    id: 7,
    nameCn: '迷宫饭',
    name: 'Dungeon Meshi',
    imageUrl: 'https://picsum.photos/seed/dungeon/300/460',
    airDate: '2024-01-04',
    ratingScore: 8.9,
    votes: 2760,
    rank: 52,
    summary: '莱欧斯一行在地下城挑战炎龙，妹妹法琳被炎龙吞噬。',
  ),
  const MockBangumiItem(
    id: 8,
    nameCn: '我推的孩子 第二季',
    name: 'Oshi no Ko 2nd Season',
    imageUrl: 'https://picsum.photos/seed/oshinoko2/300/460',
    airDate: '2024-07-03',
    ratingScore: 7.5,
    votes: 2100,
    rank: 610,
    summary: '阿库亚继续追查母亲被害的真相。',
  ),
  const MockBangumiItem(
    id: 9,
    nameCn: '孤独摇滚！',
    name: 'Bocchi the Rock!',
    imageUrl: 'https://picsum.photos/seed/bocchi/300/460',
    airDate: '2022-10-09',
    ratingScore: 8.8,
    votes: 6100,
    rank: 38,
    summary: '后藤一里是一个喜欢吉他的孤独少女。在家里练习着，以网络上的「吉他英雄」闻名。',
  ),
  const MockBangumiItem(
    id: 10,
    nameCn: '别当欧尼酱了！',
    name: 'Onimai: I\'m Now Your Sister!',
    imageUrl: 'https://picsum.photos/seed/onimai/300/460',
    airDate: '2023-01-05',
    ratingScore: 7.6,
    votes: 1800,
    rank: 530,
    summary: '家里蹲的绪山真寻一觉醒来变成了美少女。',
  ),
  const MockBangumiItem(
    id: 11,
    nameCn: '无职转生 第二季',
    name: 'Mushoku Tensei II',
    imageUrl: 'https://picsum.photos/seed/mushoku2/300/460',
    airDate: '2023-07-02',
    ratingScore: 8.3,
    votes: 3200,
    rank: 175,
    summary: '被冲击波分散的鲁迪乌斯，到达了魔大陆。',
  ),
  const MockBangumiItem(
    id: 12,
    nameCn: '辉夜大小姐想让我告白 第三季',
    name: 'Kaguya-sama wa Kokurasetai: Ultra Romantic',
    imageUrl: 'https://picsum.photos/seed/kaguya3/300/460',
    airDate: '2022-04-09',
    ratingScore: 9.0,
    votes: 4800,
    rank: 22,
    summary: '秀知院学园学生会，副会长四宫辉夜与会长白银御行的恋爱头脑战。',
  ),
  const MockBangumiItem(
    id: 13,
    nameCn: 'Re：从零开始的异世界生活 第三季',
    name: 'Re:Zero kara Hajimeru Isekai Seikatsu 3rd Season',
    imageUrl: 'https://picsum.photos/seed/rezero3/300/460',
    airDate: '2024-10-02',
    ratingScore: 8.1,
    votes: 1900,
    rank: 280,
    summary: '菜月昴再次面临新的试炼。',
  ),
  const MockBangumiItem(
    id: 14,
    nameCn: '尖帽子的魔法工房',
    name: 'Tongari Boushi no Atelier',
    imageUrl: 'https://picsum.photos/seed/atelier/300/460',
    airDate: '2025-04-04',
    ratingScore: 8.5,
    votes: 1200,
    rank: 145,
    summary: '在这个世界上，能够使用魔法的只有受过特殊训练的魔法使。',
  ),
  const MockBangumiItem(
    id: 15,
    nameCn: '婚姻剧毒',
    name: 'Marriage Toxin',
    imageUrl: 'https://picsum.photos/seed/marriage/300/460',
    airDate: '2025-04-06',
    ratingScore: 6.7,
    votes: 1560,
    rank: 3922,
    summary: '暗杀组织的杀手与毒师的联姻故事。',
  ),
  const MockBangumiItem(
    id: 16,
    nameCn: '杖与剑的魔剑谭 第二季',
    name: 'Tsue to Tsurugi no Wistoria 2nd Season',
    imageUrl: 'https://picsum.photos/seed/wistoria2/300/460',
    airDate: '2025-04-07',
    ratingScore: 7.0,
    votes: 980,
    rank: 1200,
    summary: '少年威尔继续追寻成为魔法使的梦想。',
  ),
  const MockBangumiItem(
    id: 17,
    nameCn: '女神"异世界转生想成为什么',
    name: 'Megami no Café Terrace',
    imageUrl: 'https://picsum.photos/seed/megami/300/460',
    airDate: '2025-04-05',
    ratingScore: 6.9,
    votes: 870,
    rank: 2100,
    summary: '女神转生异世界的奇妙冒险。',
  ),
  const MockBangumiItem(
    id: 18,
    nameCn: '物语系列 Off & Monster Season',
    name: 'Monogatari Series: Off & Monster Season',
    imageUrl: 'https://picsum.photos/seed/monogatari/300/460',
    airDate: '2024-07-06',
    ratingScore: 8.2,
    votes: 2400,
    rank: 200,
    summary: '怪异故事的新篇章。',
  ),
  const MockBangumiItem(
    id: 19,
    nameCn: '夏日重现',
    name: 'Summer Time Rendering',
    imageUrl: 'https://picsum.photos/seed/summertime/300/460',
    airDate: '2022-04-15',
    ratingScore: 8.7,
    votes: 3900,
    rank: 78,
    summary: '网代慎平回到故乡日都�的小岛，参加青梅竹马小舟潮的葬礼。',
  ),
  const MockBangumiItem(
    id: 20,
    nameCn: '86 -不存在的战区-',
    name: '86: Eighty Six',
    imageUrl: 'https://picsum.photos/seed/eightysix/300/460',
    airDate: '2021-04-11',
    ratingScore: 8.5,
    votes: 3100,
    rank: 110,
    summary: '圣玛格诺利亚共和国宣称与邻国的战争没有人员伤亡，但实际上……',
  ),
];
